name: Cleopatra
favicon: null
layout_spectrum: 0.2359
typography_spectrum: 0.02999739209190011
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffe08d'
    - '#a54e1a'
    - '#8aa381'
    - '#df0000'
  brandStrength: 0.9188126516528428
  lightness: 0.38663881504908204
  saturation: 0.09496677853167057
  rhythmicContrast: 0.22865178319625556
purpose: []
